export const YOUTUBE_IDS = [
  "x2BwY40EYp8",
  "tUiFUJFQZKo",
  "gcPJH-qQ7To",
  "qK38nPgaQ2U",
  "TcIjPPrwX4U",
  "LCqBUv5TJ0U",
  "MkJgqkp_DRM",
  "-mQ5AE5EMFg",
  "k70PAc_qsi8",
  "8J0_yJ4SDYs",
  "RNJhm72AEnI",
  "ga66siYwX7U",
  "Jb3XHHcmFlw",
  "6jCmv1sACVU",
  "HpaNtWOLfpA",
  "7R1H-3yCgdY",
  "xXSegSKXfSY",
  "FiYWmBdBhxs",
  "ZHk8w8fCy2I",
  "eqxk2rVPbdA",
  "GDcdFtZExzM",
  "dDHPkaJXHQg",
] as const;
